attributes:
  include.in.token.scope: 'false'
  display.on.consent.screen: 'false'
description: Specific scope for a client enabled for service accounts
id: service_account
name: service_account
protocol: openid-connect
protocolMappers:
- config:
    user.session.note: client_id
    introspection.token.claim: 'true'
    id.token.claim: 'true'
    access.token.claim: 'true'
    claim.name: client_id
    jsonType.label: String
  id: 9edf5243-8854-42ba-9bdb-c7658cda8fe3
  isUpdated: false
  name: Client ID
  protocolMapper: oidc-usersessionmodel-note-mapper
- config:
    user.session.note: clientHost
    introspection.token.claim: 'true'
    id.token.claim: 'true'
    access.token.claim: 'true'
    claim.name: clientHost
    jsonType.label: String
  id: 65d27318-c9cc-46fe-bc29-ce1d10ffdafd
  isUpdated: false
  name: Client Host
  protocolMapper: oidc-usersessionmodel-note-mapper
- config:
    user.session.note: clientAddress
    introspection.token.claim: 'true'
    id.token.claim: 'true'
    access.token.claim: 'true'
    claim.name: clientAddress
    jsonType.label: String
  id: 45285229-e3c1-4c7a-8daa-cd84ccdfd695
  isUpdated: false
  name: Client IP Address
  protocolMapper: oidc-usersessionmodel-note-mapper
realmId: demo
scopeMappings: []
