alwaysDisplayInConsole: null
attributes: {}
authenticationFlowBindingOverrides: {}
baseUrl: null
bearerOnly: true
clientAuthenticatorType: client-secret
clientId: realm-management
clientScopes:
  web-origins: true
  acr: true
  address: false
  phone: false
  profile: true
  roles: true
  offline_access: false
  microprofile-jwt: false
  basic: true
  email: true
consentRequired: null
description: null
directAccessGrantsEnabled: null
enabled: true
frontchannelLogout: null
fullScopeAllowed: false
id: realm-management
implicitFlowEnabled: null
managementUrl: null
multiValueAttributes: {}
name: ${client_realm-management}
nodeReRegistrationTimeout: null
notBefore: null
protocol: openid-connect
protocolMappers: []
publicClient: null
realmId: demo
redirectUris: []
registrationToken: null
rootUrl: null
scope: []
scopeMappings: []
secret: null
serviceAccountsEnabled: null
standardFlowEnabled: true
surrogateAuthRequired: null
updated: false
webOrigins: []
