apiVersion: k8store.dominikschlosser.github.io/v1alpha1
kind: KeycloakClient
metadata:
  name: master.demo-realm
  labels:
    k8store.dominikschlosser.github.io/keycloak-version: 26.7.0
    k8store.dominikschlosser.github.io/realm: master
spec:
  bearerOnly: true
  clientAuthenticatorType: client-secret
  clientId: demo-realm
  enabled: true
  id: demo-realm
  name: demo Realm
  realm: master
  standardFlowEnabled: true
