attributes:
  include.in.token.scope: 'false'
  display.on.consent.screen: 'false'
description: Specific scope for a client enabled for service accounts
id: service_account
name: service_account
protocol: openid-connect
protocolMappers:
- config:
    user.session.note: client_id
    introspection.token.claim: 'true'
    id.token.claim: 'true'
    access.token.claim: 'true'
    claim.name: client_id
    jsonType.label: String
  id: d0f2c3cd-cdc6-4494-a129-d63f10e2fa03
  isUpdated: false
  name: Client ID
  protocolMapper: oidc-usersessionmodel-note-mapper
- config:
    user.session.note: clientHost
    introspection.token.claim: 'true'
    id.token.claim: 'true'
    access.token.claim: 'true'
    claim.name: clientHost
    jsonType.label: String
  id: 2aabb2e0-e40d-4c37-b0ce-f0dc060bf66f
  isUpdated: false
  name: Client Host
  protocolMapper: oidc-usersessionmodel-note-mapper
- config:
    user.session.note: clientAddress
    introspection.token.claim: 'true'
    id.token.claim: 'true'
    access.token.claim: 'true'
    claim.name: clientAddress
    jsonType.label: String
  id: dad7c6bc-c455-4b5d-a48e-78bd1a81ecd9
  isUpdated: false
  name: Client IP Address
  protocolMapper: oidc-usersessionmodel-note-mapper
realmId: master
scopeMappings: []
