attributes: {}
clientId: demo-realm
compositeRoles: []
description: ${role_view-identity-providers}
id: demo-realm:view-identity-providers
name: view-identity-providers
realmId: master
updated: false
