attributes: {}
clientId: realm-management
compositeRoles:
- realm-management:create-client
- realm-management:view-realm
- realm-management:view-users
- realm-management:view-clients
- realm-management:view-events
- realm-management:view-identity-providers
- realm-management:view-authorization
- realm-management:view-organizations
- realm-management:manage-realm
- realm-management:manage-users
- realm-management:manage-clients
- realm-management:manage-events
- realm-management:manage-identity-providers
- realm-management:manage-authorization
- realm-management:manage-organizations
- realm-management:query-users
- realm-management:query-clients
- realm-management:query-realms
- realm-management:query-groups
- realm-management:query-organizations
- realm-management:impersonation
description: ${role_realm-admin}
id: realm-management:realm-admin
name: realm-admin
realmId: demo
updated: false
