attributes: {}
clientId: demo-realm
compositeRoles: []
description: ${role_manage-identity-providers}
id: demo-realm:manage-identity-providers
name: manage-identity-providers
realmId: master
updated: false
