attributes: {}
clientId: demo-realm
compositeRoles:
- demo-realm:query-organizations
description: ${role_view-organizations}
id: demo-realm:view-organizations
name: view-organizations
realmId: master
updated: false
